# Generated by Django 3.1.5 on 2021-01-28 14:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('date_of_signup', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a programming language (e.g. python, C etc.)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date_of_first_submit', models.DateField(auto_now_add=True)),
                ('date_of_latest_submit', models.DateField(auto_now_add=True)),
                ('code_lines', models.PositiveSmallIntegerField()),
                ('execute_result', models.BooleanField()),
                ('execute_time', models.TimeField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='practice_boards.author')),
                ('code_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='practice_boards.codelanguage')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='practices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='practice_boards.practice'),
        ),
    ]
