# Generated by Django 3.1.5 on 2021-01-28 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice_boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='practices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='practice_boards.practice'),
        ),
    ]
