# Generated by Django 3.1.5 on 2021-01-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_boards', '0002_auto_20210128_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='execute_result',
            field=models.CharField(max_length=20),
        ),
    ]
