# Generated by Django 3.1.5 on 2021-01-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_boards', '0003_auto_20210128_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='upload',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
